### ISSUE TITLE
vtkplotter.dolfin

### ISSUE THREAD

**Issue by marcomusy** [cako/fenics-scripts#1]
@cako 
Hi Carlos, I adapted you great script for the [ `vtkplotter.dolfin` ](https://github.com/marcomusy/vtkplotter/tree/master/examples/other/dolfin)I hope you don't mind!
It looks really cool:
![](https://user-images.githubusercontent.com/32848391/58368591-8b3fab80-7eef-11e9-882f-8b8eaef43567.gif)
[awefem.py](https://github.com/marcomusy/vtkplotter/tree/master/examples/other/dolfin)

Btw, what is this line doing?
`solver.parameters['reuse_factorization'] = True`
in fenics 2018 the parameter is not there..

**Comment by cako** [comment]
Hi @marcomusy ,

Sorry about the delay in getting back to you, slipped my mind! As far as I remember that flag allowed the LU factorization to be reused at each step so it wouldn't have to be recomputed. I believe it can be dropped with no problems.

Happy to see the script being used and it looks like you have a great collection going on there.

Best,

@cako

**Comment by marcomusy** [comment]
Hi @cako 
thanks:), i might be wrong but the substitute for that could be mumps
solver = LUSolver(A, "mumps")
cheers,
m.
